### ISSUE TITLE
Store and return the current best loss from sciml_train on Flux.jl optimizers

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#170]
By default, some Flux optimizers don't always move forward due to stochastic optimization. In these cases, you can have the loss jiggle, so you don't necessarily return the parameters with the lowest loss if you return the last parameters. However, we can store the current best and then manually return the true best at the end of the optimization.

**Comment by dhairyagandhi96** [comment]
Seems like a good utility to have in Flux, @MikeInnes?

**Comment by MikeInnes** [comment]
This just seems like a way to overfit to the test set. The fluctuations after an optimiser has converged likely just represent noise caused by the minibatches, and don't reflect true performance (i.e. on new data rather than just the test set).

Besides that there's the technical issue of having to make copies of a (potentially large) model. So I don't think we could or should do this by default, but perhaps if someone can design a separate utility and show that it's sound we could consider it.
