### ISSUE TITLE
Neural DAE tests not included in runtests and outdated 

### ISSUE THREAD

**Issue by Vaibhavdixit02** [SciML/DiffEqFlux.jl#425]
The test at https://github.com/SciML/DiffEqFlux.jl/blob/master/test/neural_dae.jl doesn't work and isn't being tested, I'll look into updating it this week, unless someone beats me to it.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqFlux.jl/pull/426 is at least a start. But the problem is more picking an appropriate architecture: it's clear what it should be in mass matrix form, it's not clear how to make it right for an arbitrary implicit form, so the mass matrix form will pretty much always be more stable.
