### ISSUE TITLE
Discretize-Optimize vs Optimize-Discretize 

### ISSUE THREAD

**Issue by finmod** [SciML/DiffEqFlux.jl#463]
In https://arxiv.org/abs/2005.13420 Onken and Ruthotto conclude using some of the examples in DiffEqFlux that Disc-Opt methods can achieve similar performance to Opt-Disc at inference with drastically reduced training costs. @ChrisRackauckas Can you show in the DiffEqFlux docs and examples that this issue has been addressed and debunked? 

Also in the NeuralODE examples, it would be good to conclude using Benchmarktools which algorithm between sciml.train and Flux.train is best. I could not find a punchline to this effect.

**Comment by ChrisRackauckas** [comment]
This is why we have the TrackerAdjoint and ReverseDiffAdjoint methods, which are auto-diff methods without these issues. The UDE paper has a whole paragraph explaining this:

>Previous research has shown that the discrete adjoint approach is more stable
>than continuous adjoints in some cases [41, 37, 42, 43, 44, 45] while continuous
>adjoints have been demonstrated to be more stable in others [46, 43] and can
>reduce spurious oscillations [47, 48, 49]. This trade-off between discrete and
>continuous adjoint approaches has been demonstrated on some equations as a
>trade-off between stability and computational efficiency [50, 51, 52, 53, 54, 55,
>56, 57, 58]. Care has to be taken as the stability of an adjoint approach can
>be dependent on the chosen discretization method [59, 60, 61, 62, 63], and our
>software contribution helps researchers switch between all of these optimization
>approaches in combination with hundreds of differential equation solver methods
>with a single line of code change.

So it's not really even a new area to study: it's pretty well established that there is an accuracy vs speed trade-off in a lot of cases, and you should choose the appropriate adjoint. There's then a whole page on this:

https://diffeqflux.sciml.ai/dev/ControllingAdjoints/

and then you should see the whole discussion in the Cornell SCAN seminar:

https://youtu.be/AIX8ardhAxA

One other thing to mention is the effect of tolerance on the ODE adjoint, which we're doing a longer study with. But I think there's sufficient information out there to say:

1) There's a trade-off
2) We have all 3 methods: continuous unstable, continuous stable, and discrete adjoint
3) They all have different use cases

If any of that isn't clear, let me know. But I would think that by now it's fairly clear.

**Comment by ChrisRackauckas** [comment]
It's also worth noting that in the old study that @donken did (https://github.com/EmoryMLIP/DOvsOD_NeuralODEs), it used the early versions of the adjoints where `neural_ode` defaulted to what we now call `BacksolveAdjoint` from the Neural ODE paper. That method is so error prone that we had to remove it from being the default, and so we now always default to `InterpolatingAdjoint` and/or `QuadratureAdjoint`. So that's another confounding factor in there, that it's a very clear reason why using `BacksolveAdjoint` should be a user opt-in for very specific cases, but even before that study came out we had deprecated `neural_ode` for direct adjoints on `solve` and when doing so changed the default adjoints for the reasons described in the SCAN seminar (difficulties with large Lipschitz constants and cases where you have unconditional instability).

We're following up with an in-depth discussion of all of the adjoint techniques together, but there's a landscape of >40 methods that can happen due to combinatorics so it's quite a chunky study. That said, it's once again demonstrating the trade-off, and how to take that trade-off is up to the user. So there's really nothing to debunk, it's more about engineering trade-offs.

**Comment by finmod** [comment]
Chris, All of this is excellent particularly the video at Cornell. I had no doubt that this issue had been addressed. 

It is just that the explanations are all spread out in the Rackaukas galaxy: SciML, mitamath 18337, Next Journal, UDE paper that it is difficult for some newbie entering the tutorial in DiffEqFlux to imagine that there is so much hidden under the hood!

A practical suggestion is that there be a short sentence of warning in the tutorials, particularly the first tutorial, that these issue exists even though they can be skipped in the initial stages of using DiffEqFlux. 
A second suggestion is that the output verbose of functions should spit out a resume of kwags and defaults that are in effect at the time of running.  Concerning `BacksolveAdjoint` , you have to get there https://github.com/SciML/DiffEqDocs.jl/blob/master/docs/src/analysis/sensitivity.md to realize that it is the default sensealg. Again the newbie is getting a lot more trouble than he asked for in the initial tutorial of DiffEqFlux.

**Comment by ChrisRackauckas** [comment]
>Concerning BacksolveAdjoint , you have to get there https://github.com/SciML/DiffEqDocs.jl/blob/master/docs/src/analysis/sensitivity.md to realize that it is the default sensealg. Again the newbie is getting a lot more trouble than he asked for in the initial tutorial of DiffEqFlux.

That's not the default because of its stability issues. If you read that page again you'll see it says `InterpolatingAdjoint` is the default. 

>difficult for some newbie entering the tutorial in DiffEqFlux to imagine that there is so much hidden under the hood!

It's kind of what we want haha. The more work we add, the less magic users will actually see.
