### ISSUE TITLE
:nothing initialised in FastChain

### ISSUE THREAD

**Issue by MatisPatel** [SciML/DiffEqFlux.jl#593]
Hey I'm having some issues running the base examples from the docs. The problem seems to be FastChain initialising some parameters as `:nothing`. MWE:

```julia
using DiffEqFlux
U = FastChain(
    FastDense(2,5),   
    FastDense(2,5))
@show intitial_params(U)

# initial_params(U) = Union{Nothing, Float32}...
```

**Comment by KirillZubov** [comment]
oh, it's the same problem https://github.com/SciML/DiffEqFlux.jl/issues/594

**Comment by ChrisRackauckas** [comment]
@DhairyaLGandhi has this been fixed?

**Comment by DhairyaLGandhi** [comment]
The fix for the nothings is in https://github.com/FluxML/Flux.jl/pull/1670 and ref https://github.com/SciML/DiffEqFlux.jl/pull/592

However, the error seen in https://github.com/SciML/DiffEqFlux.jl/pull/592/checks?check_run_id=3128353069 comes from https://github.com/FluxML/Flux.jl/blob/186f7484a4c9df8e18dc2eb0fe35d3fe82b30d9c/src/losses/utils.jl#L27 which was from https://github.com/FluxML/Flux.jl/pull/1636 and that would still break the Newton tests.

**Comment by DhairyaLGandhi** [comment]
The `nothing` issue should be fixed on Flux master

**Comment by MatisPatel** [comment]
Hey sorry for the novice question but can I get julia use master branch rather than release? `add Flux` gives me v0.12.5

**Comment by ChrisRackauckas** [comment]
You shouldn't have to grab master. Why isn't Flux just doing a release?

**Comment by DhairyaLGandhi** [comment]
I was just about to schedule a release before I saw activity here :)

As noted, it doesn't fix the tests that fail.

**Comment by ChrisRackauckas** [comment]
What's the deal with the Newton test? What adjoint is the one throwing the error/warning?

**Comment by DhairyaLGandhi** [comment]
Close?
