### ISSUE TITLE
Neural ODE example is not working correctly

### ISSUE THREAD

**Issue by MilkshakeForReal** [SciML/DiffEqFlux.jl#731]
https://diffeqflux.sciml.ai/dev/examples/neural_ode/
```julia
ERROR: MethodError: no method matching LBFGS(; initial_stepnorm=0.01)
Closest candidates are:
  LBFGS(; m, alphaguess, linesearch, P, precondprep, manifold, scaleinvH0) at C:\Users\Luffy\.julia\packages\Optim\6Lpjy\src\multivariate\solvers\first_order\l_bfgs.jl:122 got unsupported keyword argument "initial_stepnorm"
  LBFGS(::Int64, ::IL, ::L, ::T, ::Tprep, ::Manifold, ::Bool) where {T, IL, L, Tprep} at C:\Users\Luffy\.julia\packages\Optim\6Lpjy\src\multivariate\solvers\first_order\l_bfgs.jl:81 got unsupported keyword argument "initial_stepnorm"
```

**Comment by Vaibhavdixit02** [comment]
Yeah that's incorrect, LBFGS doesn't have `initial_stepnorm` as a field

**Comment by ChrisRackauckas** [comment]
Yes sorry about that. After the Optimization change I think I merged a PR to the docs that broke all of the tutorials, so I'm racing against the clock to update them and make sure they are all doc tested. 

https://github.com/SciML/DiffEqFlux.jl/pull/721/
https://github.com/SciML/DiffEqSensitivity.jl/pull/623
https://github.com/SciML/DiffEqSensitivity.jl/pull/636

I figured out that we needed to add the `strict` block to make them cause a CI failure https://github.com/SciML/DiffEqFlux.jl/pull/721/files#diff-4aae2d1c783cade58bd2cb13748da956e568b7f2aed5fafd9e2a46fb97daf613R14-R18 otherwise they will throw text but no CI failure error, and I was just looking for the green checkmark 😅.
