### ISSUE TITLE
DiffEqFlux.jl and NeuralPDE.jl keep precompiling and never stop

### ISSUE THREAD

**Issue by Song921012** [SciML/DiffEqFlux.jl#783]
Environment:
```
 ] activate --temp
add DiffEqFlux
```
`DiffEqFlux.jl` will keep precompiling and never stop (at least 20mins). I think the reason may be the update of `Zygote.jl` hours ago (from 0.6.49 to 0.6.50)?  When I downgrade  `Zygote.jl`. It is normal.   I am not sure.

```
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 6
  LD_LIBRARY_PATH = /usr/lib/cuda/lib64:/opt/copt60/lib:/usr/local/lib64:/opt/openrobots/lib:/home/aidishage/myenv/lib
  JULIA_PARDISO = /home/aidishage/myenv/lib
  JULIA_PYTHONCALL_EXE = @PyCall
  JULIA_CONDAPKG_BACKEND = Null
  JULIA_EDITOR = lvim
```

**Comment by ChrisRackauckas** [comment]
That sounds downstream and should be reported to Zygote.jl? Does it happen if you just `using Zygote`?

**Comment by Song921012** [comment]
> That sounds downstream and should be reported to Zygote.jl? Does it happen if you just `using Zygote`?

```
]activate --temp
add Zygote
using Zygote
```
It works well.

**Comment by aelmokadem** [comment]
This started happening with me too a few hours ago!

**Comment by ChrisRackauckas** [comment]
Zygote added some precompilation stuff in the latest patch: https://github.com/FluxML/Zygote.jl/pull/1281. Something might be up with some of that.

**Comment by ChrisRackauckas** [comment]
Can you try `dev`ing Zygote and removing that SnoopPrecompilation block and seeing if that fixes it?

**Comment by Song921012** [comment]
@ChrisRackauckas Chris, you are right. I comment
```
using SnoopPrecompile
@precompile_all_calls precompile()
```
It solved the problem. However, it seems that no complicated functions are precompiled in`precompile.jl`, don't understand why it happened.

**Comment by ToucheSir** [comment]
Note that the precompilation changes were added in the 2nd last patch, not 0.6.50. If anyone's code was working with 0.6.49, it was working with precompilation. This includes DiffEqFlux's [own CI](https://github.com/SciML/DiffEqFlux.jl/actions/runs/3551099864/jobs/5965033726#step:6:375) (which also imports the latest Lux version, which is contrary to what folks are experiencing locally). So whatever change happened to induce this never-ending precompile issue, it has to be caused by the interaction of some factor which doesn't show up on this specific package's CI but does locally and with other packages.

[This](https://github.com/FluxML/Zygote.jl/compare/v0.6.49...v0.6.50) is the totality of the changes between 0.6.49 and 0.6.50, and you can see nothing touched precomp or the compiler. Therefore, I suspect the issue is a deeper one between SnoopPrecompile, Base and whatever environmental factors/external dependencies are the trigger for this issue.

**Comment by avik-pal** [comment]
On CI for both [0.6.50](https://github.com/avik-pal/Lux.jl/actions/runs/3550482607/jobs/5993305398) and [v0.6.51](https://github.com/avik-pal/Lux.jl/actions/runs/3566739728/jobs/5993567131), precompilation works out fine. But locally, I can reproduce the problem with Lux + Zygote 0.6.50, which gets stuck but 0.6.51 finishes as expected.

Also, terminating the precompilation and then doing `using Lux` again seems to work in the former case :shrug:

**Comment by ToucheSir** [comment]
I tested again with 0.6.50 or the SnoopPrecompile changes unreverted, and I can no longer repro the precompilation freeze on 1.8.5. @avik-pal and @Song921012, can you test again on your end? If successful, we should slip the switch on again.

**Comment by ToucheSir** [comment]
Just checking, is that a "yes this works now" or just cleaning up old issues?

**Comment by ChrisRackauckas** [comment]
I at least cannot reproduce it.
