### ISSUE TITLE
Including parameters in NeuralODE

### ISSUE THREAD

**Issue by MaAl13** [SciML/DiffEqFlux.jl#798]
Hello,

is there a way to incorporate parameters in the NeuralODE? I want to use the NeuralODE as a surrogate model, that gives me the trajectory of problem at specific time points, depending on the parameters. I have a few thousand trajectories of the forward problem given at time points, for specific parameters, to train the NeuralODE. Would be happy if someone could help me out!

**Comment by ChrisRackauckas** [comment]
Just append them to the vector? There's nothing extra to do here other than choose an architecture which makes sense. For example, instead of defining the neural ODE as `f(u,p,t) = NN(u)`, you can just do `f(u,p,t) = NN([u;p])`, so then the parameters of the ODE are `p = [model_parameters ; neuralnet_weights]`

**Comment by ChrisRackauckas** [comment]
Handled by the ComponentArray and tutorials in SciMLSensitivity.
